### ISSUE TITLE
RSU vs RCU?

### ISSUE THREAD

**Issue by BraveCaperCat2** [factorio-plexpt/real-starry-universe#1]
Is this mod called Real Starry Universe or Real Celestial Universe? The readme.md file doesn't make this very clear...

**Comment by PlexPt** [comment]
which better ?

**Comment by BraveCaperCat2** [comment]
Real Celestial Universe (because it's also a rocket control unit)

**Comment by BraveCaperCat2** [comment]
Fixed by #2
