### ISSUE TITLE
about real astronomical data

### ISSUE THREAD

**Issue by PlexPt** [factorio-plexpt/real-starry-universe#10]
> You do know I spent forever getting the precise values for all of this and you just round it away...
> 
> 
> 
>  This commit only makes the realism of the mod less-real.
> 
> 
> 
> I thought this mod was for having real astronomical data for everything and you just go and ruin that. 

 _Originally posted by @BraveCaperCat2 in [f0ff665](https://github.com/factorio-plexpt/real-starry-universe/commit/f0ff6650f6661324e8cd845a2f94964ee4e58dfe#commitcomment-149775816)_

I'm sorry, I understand your emphasis on precision. However, in astronomy, we typically use average values rather than exact ones. This is because astronomical data is influenced by various factors such as limitations of observational equipment and atmospheric interference, making it impossible to obtain absolutely precise values. Using averages can better represent the overall trend of the data and reduce errors caused by individual outliers. I will try to maintain data accuracy in future updates while also considering the commonly used data representation methods in astronomy. Thank you once again for your feedback and understanding.

**Comment by BraveCaperCat2** [comment]
I mean... ok.

**Comment by PlexPt** [comment]
Do you need to send a PR?

**Comment by BraveCaperCat2** [comment]
I sent PR #12 just recently. It will need "Averaging" since most of the values were added before commit [f0ff665](https://github.com/factorio-plexpt/real-starry-universe/commit/f0ff6650f6661324e8cd845a2f94964ee4e58dfe#commitcomment-149775816).

**Comment by BraveCaperCat2** [comment]
Fixed by #10.
