### ISSUE TITLE
TODO: There are too many planets in the new game menu. Reduce them appropriately.

### ISSUE THREAD

**Issue by PlexPt** [factorio-plexpt/real-starry-universe#25]
There are too many planets in the new game menu. Reduce them appropriately.

### How to Start

**Before Starting:**
If you are interested in taking on this task,  simply comment below with the following information:
1. Your estimated timeline for completing the task
2. Any questions or clarifications you may have

Thank you for considering this task!

**Comment by PlexPt** [comment]
![image](https://github.com/user-attachments/assets/1abfaf63-883f-473b-b2c8-af3f2f494e57)

**Comment by BraveCaperCat2** [comment]
Unfortunately, I don't know how to fix this. Do you know of any other mods which add lots of planets and don't have so many planets on the map creation screen?
Here is a [Relevant Topic on the Factorio Forums](https://forums.factorio.com/viewtopic.php?f=7&t=123043).

**Comment by PlexPt** [comment]
Temporarily remove map_gen_settings.autoplace_controls for all placeholder planets

**Comment by BraveCaperCat2** [comment]
Ah, ok.

1. About 20 minutes
2. No (more) clarifications needed.
