### ISSUE TITLE
[BUG] Asteroid belt image + Visible Planets In Space

### ISSUE THREAD

**Issue by BraveCaperCat2** [factorio-plexpt/real-starry-universe#30]
### Description
When I go to the Main Asteroid Belt or the Kuiper Belt with the Visible Planets In Space mod, you see the asteroid image as part of the background.

### Steps to Reproduce
1. Download and install Visible Planets
2. Restart your game to apply the changes.
3. Send a space platform to either asteroid belt.
4. See the image.

### Expected Behaviour
I expected to not see the asteroid image in the background with the Visible Planets In Space mod installed.

### Actual Behaviour
I saw the asteroid image in the background with the Visible Planets In Space mod installed.

### Screenshots
![Screenshot 2024-12-07 133515](https://github.com/user-attachments/assets/a5a34423-a306-4831-b96a-4d98d179f4fc)
![Screenshot 2024-12-07 133924](https://github.com/user-attachments/assets/9aa6ec53-ed63-4598-a8c4-9f6782753e31)

### Environment
- Factorio Space Age.
- In development version of RSU.
- Visible Planets In Space mod.

### Additional Context
It's possible that this issue can only be fixed by the Visible Planets In Space mod's developer(s).

**Comment by PlexPt** [comment]
I don't think it's a bug, it's by design.

**Comment by BraveCaperCat2** [comment]
maybe, but the asteroid image looks weird here.

**Comment by BraveCaperCat2** [comment]
Done.
![Screenshot 2024-12-08 114616](https://github.com/user-attachments/assets/51001eee-ca34-4fb2-a531-ad2859334aaa)

**Comment by BraveCaperCat2** [comment]
Fixed by #33
