### ISSUE TITLE
Distance

### ISSUE THREAD

**Issue by BraveCaperCat2** [factorio-plexpt/real-starry-universe#7]
The distances between planets are extremely short. For instance, the distance along the space route between mercury and venus is only 500km, when the average distance between them is at most 7,798,431km.

I'm already going to work on this.

**Comment by PlexPt** [comment]
ok

**Comment by BraveCaperCat2** [comment]
It isn't perfect yet, but good enough for now:
![Screenshot 2024-11-26 194417](https://github.com/user-attachments/assets/c790d49f-118e-4363-b239-39238af37db9)

**Comment by PlexPt** [comment]
maybe you need a discord

**Comment by PlexPt** [comment]
There are 20 people in the Discord group now.

**Comment by BraveCaperCat2** [comment]
Wait... I can no longer travel between the planets of the inner solar system because they're too far apart.

**Comment by BraveCaperCat2** [comment]
Done. Where can I find the invite/link/whatever it is?

**Comment by PlexPt** [comment]
https://discord.gg/rmw4GMqe
